### ISSUE TITLE
关于显示生成图像的展示

### ISSUE THREAD

**Issue by panicwq** [LynnHo/DCGAN-LSGAN-WGAN-GP-DRAGAN-Pytorch#1]
您好，我对您们的程序很感兴趣。
有一个问题，默认图像生成展示是10*10，如果想训练到一定程度时一个一个的展示图片该怎么办？
我尝试把row_n这个参数改成1，但是结果变成了一行拼接起来的图片。

请问我该怎么做，非常感谢！

**Comment by LynnHo** [comment]
@panicwq 改一下这个地方，循环把图片一个一个存就可以，`x_fake`就是一批图片，这一行只不过是拼起来
https://github.com/LynnHo/DCGAN-LSGAN-WGAN-GP-DRAGAN-Pytorch/blob/be05f7d0a32b571f899e4aa82135465262a0a7f7/train.py#L205
